// AUTO-GENERATED by scripts/gen-shows.mjs — do not edit by hand.
// Curated pool of shows for the "More shows" related-links block and the sitemap.
// Regenerate: node --env-file=.env scripts/gen-shows.mjs
export interface ShowRef {
  id: string;
  name: string;
  genres: string[];
}

export const SHOWS: ShowRef[] = [
  {
    "id": "75692",
    "name": "Law & Order: Special Victims Unit",
    "genres": [
      "Drama",
      "Crime",
      "Thriller",
      "Mystery"
    ]
  },
  {
    "id": "73244",
    "name": "The Office (US)",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "79169",
    "name": "Seinfeld",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "71663",
    "name": "The Simpsons",
    "genres": [
      "Comedy",
      "Animation"
    ]
  },
  {
    "id": "79168",
    "name": "Friends",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "81189",
    "name": "Breaking Bad",
    "genres": [
      "Drama",
      "Crime",
      "Thriller",
      "Western"
    ]
  },
  {
    "id": "75805",
    "name": "It's Always Sunny in Philadelphia",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "77398",
    "name": "The X-Files",
    "genres": [
      "Science Fiction",
      "Horror",
      "Fantasy",
      "Drama"
    ]
  },
  {
    "id": "77623",
    "name": "Cheers",
    "genres": [
      "Drama",
      "Comedy"
    ]
  },
  {
    "id": "84912",
    "name": "Parks and Recreation",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "77811",
    "name": "Frasier",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "76203",
    "name": "Curb Your Enthusiasm",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "72173",
    "name": "Arrested Development",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "94571",
    "name": "Community",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "75760",
    "name": "How I Met Your Mother",
    "genres": [
      "Comedy",
      "Romance"
    ]
  },
  {
    "id": "269586",
    "name": "Brooklyn Nine-Nine",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "79488",
    "name": "30 Rock",
    "genres": [
      "Comedy"
    ]
  },
  {
    "id": "73871",
    "name": "Futurama",
    "genres": [
      "Science Fiction",
      "Comedy",
      "Animation",
      "Adventure"
    ]
  },
  {
    "id": "73903",
    "name": "King of the Hill",
    "genres": [
      "Drama",
      "Comedy",
      "Animation"
    ]
  },
  {
    "id": "75897",
    "name": "South Park",
    "genres": [
      "Comedy",
      "Animation"
    ]
  },
  {
    "id": "75978",
    "name": "Family Guy",
    "genres": [
      "Comedy",
      "Animation"
    ]
  },
  {
    "id": "194031",
    "name": "Bob's Burgers",
    "genres": [
      "Comedy",
      "Animation"
    ]
  },
  {
    "id": "358915",
    "name": "The Twilight Zone (2019)",
    "genres": [
      "Science Fiction",
      "Horror",
      "Fantasy",
      "Drama"
    ]
  },
  {
    "id": "71470",
    "name": "Star Trek: The Next Generation",
    "genres": [
      "Science Fiction",
      "Drama",
      "Adventure",
      "Action"
    ]
  },
  {
    "id": "78804",
    "name": "Doctor Who (2005)",
    "genres": [
      "Science Fiction",
      "Drama",
      "Adventure"
    ]
  },
  {
    "id": "70327",
    "name": "Buffy the Vampire Slayer",
    "genres": [
      "Horror",
      "Fantasy",
      "Drama",
      "Comedy"
    ]
  },
  {
    "id": "75299",
    "name": "The Sopranos",
    "genres": [
      "Drama",
      "Crime"
    ]
  },
  {
    "id": "79126",
    "name": "The Wire",
    "genres": [
      "Drama",
      "Crime",
      "Thriller"
    ]
  },
  {
    "id": "80337",
    "name": "Mad Men",
    "genres": [
      "Drama"
    ]
  },
  {
    "id": "72521",
    "name": "The West Wing",
    "genres": [
      "Drama"
    ]
  },
  {
    "id": "72368",
    "name": "Law & Order",
    "genres": [
      "Drama",
      "Crime"
    ]
  },
  {
    "id": "71489",
    "name": "Law & Order: Criminal Intent",
    "genres": [
      "Drama",
      "Crime",
      "Thriller",
      "Mystery"
    ]
  },
  {
    "id": "72108",
    "name": "NCIS",
    "genres": [
      "Drama",
      "Crime",
      "Adventure",
      "Action"
    ]
  },
  {
    "id": "72546",
    "name": "CSI: Crime Scene Investigation",
    "genres": [
      "Drama",
      "Crime",
      "Thriller",
      "Mystery"
    ]
  },
  {
    "id": "73255",
    "name": "House",
    "genres": [
      "Drama",
      "Suspense",
      "Mystery"
    ]
  },
  {
    "id": "70761",
    "name": "ER",
    "genres": [
      "Drama",
      "Romance"
    ]
  },
  {
    "id": "76156",
    "name": "Scrubs",
    "genres": [
      "Drama",
      "Comedy"
    ]
  },
  {
    "id": "73762",
    "name": "Grey's Anatomy",
    "genres": [
      "Soap",
      "Drama",
      "Romance"
    ]
  },
  {
    "id": "70369",
    "name": "Columbo",
    "genres": [
      "Drama",
      "Crime",
      "Thriller",
      "Mystery"
    ]
  },
  {
    "id": "78049",
    "name": "Murder, She Wrote",
    "genres": [
      "Drama",
      "Crime",
      "Mystery"
    ]
  },
  {
    "id": "70994",
    "name": "M*A*S*H",
    "genres": [
      "Drama",
      "Comedy",
      "War"
    ]
  },
  {
    "id": "70533",
    "name": "Twin Peaks",
    "genres": [
      "Horror",
      "Fantasy",
      "Drama",
      "Crime"
    ]
  }
];
