#!/usr/bin/env node
// One-off generator for src/lib/shows.ts — a static, curated pool of shows
// ({ id, name, genres }) used for the "More shows" related-links block and the
// sitemap. Baking it static means those run with zero per-request TheTVDB calls.
//
// Regenerate (or after editing TITLES):  node --env-file=.env scripts/gen-shows.mjs
// Needs TVDB_API_KEY (and optional TVDB_PIN) in .env.

import { writeFile } from 'node:fs/promises';

const BASE = 'https://api4.thetvdb.com/v4';

// Curated pool. Order is preserved; the related block rotates a window through it.
const TITLES = [
  'Law & Order: Special Victims Unit', 'The Office', 'Seinfeld', 'The Simpsons',
  'Friends', 'Breaking Bad', "It's Always Sunny in Philadelphia", 'The X-Files',
  'Cheers', 'Parks and Recreation', 'Frasier', 'Curb Your Enthusiasm',
  'Arrested Development', 'Community', 'How I Met Your Mother', 'Brooklyn Nine-Nine',
  '30 Rock', 'Futurama', 'King of the Hill', 'South Park',
  'Family Guy', "Bob's Burgers", 'The Twilight Zone', 'Star Trek: The Next Generation',
  'Doctor Who', 'Buffy the Vampire Slayer', 'The Sopranos', 'The Wire',
  'Mad Men', 'The West Wing', 'Law & Order', 'Law & Order: Criminal Intent',
  'NCIS', 'CSI: Crime Scene Investigation', 'House', 'ER',
  'Scrubs', "Grey's Anatomy", 'Columbo', 'Murder, She Wrote',
  'M*A*S*H', 'Twin Peaks',
];

async function login() {
  const apikey = process.env.TVDB_API_KEY;
  const pin = process.env.TVDB_PIN;
  if (!apikey) throw new Error('TVDB_API_KEY missing (use: node --env-file=.env scripts/gen-shows.mjs)');
  const res = await fetch(`${BASE}/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(pin ? { apikey, pin } : { apikey }),
  });
  if (!res.ok) throw new Error(`login failed (${res.status})`);
  return (await res.json())?.data?.token;
}

async function main() {
  const token = await login();
  const headers = { Authorization: `Bearer ${token}`, Accept: 'application/json' };
  const out = [];
  const seen = new Set();

  for (const title of TITLES) {
    try {
      const sr = await fetch(
        `${BASE}/search?query=${encodeURIComponent(title)}&type=series&limit=1`,
        { headers },
      ).then((r) => r.json());
      const first = sr?.data?.[0];
      const id = String(first?.tvdb_id ?? first?.id ?? '').replace(/^series-/, '');
      if (!id || seen.has(id)) {
        if (!id) console.error(`  miss: ${title}`);
        continue;
      }
      const ext = await fetch(`${BASE}/series/${id}/extended?short=false`, { headers }).then((r) => r.json());
      const genres = Array.isArray(ext?.data?.genres)
        ? ext.data.genres.map((g) => g?.name).filter(Boolean).slice(0, 4)
        : [];
      seen.add(id);
      out.push({ id, name: ext?.data?.name ?? first?.name ?? title, genres });
      console.error(`  ok: ${out[out.length - 1].name} [${genres.join(', ')}]`);
    } catch (e) {
      console.error(`  error: ${title} — ${e.message}`);
    }
  }

  const body = `// AUTO-GENERATED by scripts/gen-shows.mjs — do not edit by hand.
// Curated pool of shows for the "More shows" related-links block and the sitemap.
// Regenerate: node --env-file=.env scripts/gen-shows.mjs
export interface ShowRef {
  id: string;
  name: string;
  genres: string[];
}

export const SHOWS: ShowRef[] = ${JSON.stringify(out, null, 2)};
`;
  await writeFile(new URL('../src/lib/shows.ts', import.meta.url), body);
  console.error(`\nWrote src/lib/shows.ts with ${out.length} shows.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
